var mockLiveAppChartApps = [{
					appName1: "8 Ball Pool",
					appIcon1: "images/placeholder-app-icon-8ball.png",
					appPublisher1: "Miniclip",
					appNumberOfRatings1: "(3,247)",
					appPrice1: "$0.99",
					appGrowth1: "+10%",
					appRevDow1: "247,926",
					appNewDisplay1: "none",
					appPositionChange1: "15",
					appPositionChangeDisplay1: "inline-block",
					appName2: "Bridge Constructor",
					appIcon2: "images/placeholder-app-icon-bridge.png",
					appPublisher2: "Headup Games GmbH &amp; Co KG",
					appNumberOfRatings2: "(3,247)",
					appPrice2: "Free",
					appGrowth2: "+10%",
					appRevDow2: "146,789",
					appNewDisplay2: "none",
					appPositionChange2: "1",
					appPositionChangeDisplay2: "inline-block",
					appName3: "Clash of Clans",
					appIcon3: "images/placeholder-app-icon-clash.png",
					appPublisher3: "Supercell",
					appNumberOfRatings3: "(78,001)",
					appPrice3: "Free",
					appGrowth3: "+10%",
					appRevDow3: "102,843",
					appNewDisplay3: "none",
					appPositionChange3: "",
					appPositionChangeDisplay3: "none",
				},
				{
					appName1: "Minecraft: Pocket Edition",
					appIcon1: "images/placeholder-app-icon-minecraft.png",
					appPublisher1: "Mojang",
					appNumberOfRatings1: "(10,458)",
					appPrice1: "$2.99",
					appGrowth1: "+4%",
					appRevDow1: "156,038",
					appNewDisplay1: "none",
					appPositionChange1: "-1",
					appPositionChangeDisplay1: "inline-block",
					appName2: "Thumb Drift - Furious One Touch Car Racing",
					appIcon2: "images/placeholder-app-icon-drift.png",
					appPublisher2: "SMG Studio",
					appNumberOfRatings2: "(156)",
					appPrice2: "Free",
					appGrowth2: "+6%",
					appRevDow2: "102,356",
					appNewDisplay2: "none",
					appPositionChange2: "119",
					appPositionChangeDisplay2: "inline-block",
					appName3: "Clash Royale",
					appIcon3: "images/placeholder-app-icon.jpg",
					appPublisher3: "Supercell",
					appNumberOfRatings3: "(2,406)",
					appPrice3: "Free",
					appGrowth3: "+100%",
					appRevDow3: "60,564",
					appNewDisplay3: "inline-block",
					appPositionChange3: "",
					appPositionChangeDisplay3: "none",
				},
				{
					appName1: "Clash of Clans",
					appIcon1: "images/placeholder-app-icon-clash.png",
					appPublisher1: "Supercell",
					appNumberOfRatings1: "(78,001)",
					appPrice1: "$2.49",
					appGrowth1: "+4%",
					appRevDow1: "102,843",
					appNewDisplay1: "none",
					appPositionChange1: "",
					appPositionChangeDisplay1: "none",
					appName2: "8 Ball Pool",
					appIcon2: "images/placeholder-app-icon-8ball.png",
					appPublisher2: "Miniclip",
					appNumberOfRatings2: "(3,247)",
					appPrice2: "Free",
					appGrowth2: "+8%",
					appRevDow2: "102,843",
					appNewDisplay2: "none",
					appPositionChange2: "-2",
					appPositionChangeDisplay2: "inline-block",
					appName3: "Bridge Constructor",
					appIcon3: "images/placeholder-app-icon-bridge.png",
					appPublisher3: "Headup Games GmbH &amp; Co KG",
					appNumberOfRatings3: "(3,247)",
					appPrice3: "$0.99",
					appGrowth3: "+6%",
					appRevDow3: "46,789",
					appNewDisplay3: "none",
					appPositionChange3: "5",
					appPositionChangeDisplay3: "inline-block",
				},
				{
					appName1: "Minecraft: Pocket Edition",
					appIcon1: "images/placeholder-app-icon-minecraft.png",
					appPublisher1: "Mojang",
					appNumberOfRatings1: "(10,458)",
					appPrice1: "$1.49",
					appGrowth1: "+4%",
					appRevDow1: "102,843",
					appNewDisplay1: "none",
					appPositionChange1: "-1",
					appPositionChangeDisplay1: "inline-block",
					appName2: "Thumb Drift - Furious One Touch Car Racing",
					appIcon2: "images/placeholder-app-icon-drift.png",
					appPublisher2: "SMG Studio",
					appNumberOfRatings2: "(156)",
					appPrice2: "Free",
					appGrowth2: "+6%",
					appRevDow2: "102,356",
					appNewDisplay2: "none",
					appPositionChange2: "119",
					appPositionChangeDisplay2: "inline-block",
					appName3: "Clash Royale",
					appIcon3: "images/placeholder-app-icon.jpg",
					appPublisher3: "Supercell",
					appNumberOfRatings3: "(2,406)",
					appPrice3: "Free",
					appGrowth3: "+8%",
					appRevDow3: "30,564",
					appNewDisplay3: "none",
					appPositionChange3: "4",
					appPositionChangeDisplay3: "inline-block",
				},
				{
					appName1: "8 Ball Pool",
					appIcon1: "images/placeholder-app-icon-8ball.png",
					appPublisher1: "Miniclip",
					appNumberOfRatings1: "(3,247)",
					appPrice1: "$2.49",
					appGrowth1: "+10%",
					appRevDow1: "247,926",
					appNewDisplay1: "none",
					appPositionChange1: "15",
					appPositionChangeDisplay1: "inline-block",
					appName2: "Bridge Constructor",
					appIcon2: "images/placeholder-app-icon-bridge.png",
					appPublisher2: "Headup Games GmbH &amp; Co KG",
					appNumberOfRatings2: "(3,247)",
					appPrice2: "Free",
					appGrowth2: "+10%",
					appRevDow2: "146,789",
					appNewDisplay2: "none",
					appPositionChange2: "1",
					appPositionChangeDisplay2: "inline-block",
					appName3: "Clash of Clans",
					appIcon3: "images/placeholder-app-icon-clash.png",
					appPublisher3: "Supercell",
					appNumberOfRatings3: "(78,001)",
					appPrice3: "Free",
					appGrowth3: "+10%",
					appRevDow3: "102,843",
					appNewDisplay3: "none",
					appPositionChange3: "",
					appPositionChangeDisplay3: "none",
				},
				{
					appName1: "Minecraft: Pocket Edition",
					appIcon1: "images/placeholder-app-icon-minecraft.png",
					appPublisher1: "Mojang",
					appNumberOfRatings1: "(10,458)",
					appPrice1: "$1.49",
					appGrowth1: "+4%",
					appRevDow1: "156,038",
					appNewDisplay1: "none",
					appPositionChange1: "-1",
					appPositionChangeDisplay1: "inline-block",
					appName2: "Thumb Drift - Furious One Touch Car Racing",
					appIcon2: "images/placeholder-app-icon-drift.png",
					appPublisher2: "SMG Studio",
					appNumberOfRatings2: "(156)",
					appPrice2: "Free",
					appGrowth2: "+6%",
					appRevDow2: "102,356",
					appNewDisplay2: "none",
					appPositionChange2: "119",
					appPositionChangeDisplay2: "inline-block",
					appName3: "Clash Royale",
					appIcon3: "images/placeholder-app-icon.jpg",
					appPublisher3: "Supercell",
					appNumberOfRatings3: "(2,406)",
					appPrice3: "Free",
					appGrowth3: "+100%",
					appRevDow3: "60,564",
					appNewDisplay3: "inline-block",
					appPositionChange3: "",
					appPositionChangeDisplay3: "none",
				},
				{
					appName1: "Clash of Clans",
					appIcon1: "images/placeholder-app-icon-clash.png",
					appPublisher1: "Supercell",
					appNumberOfRatings1: "(78,001)",
					appPrice1: "Free",
					appGrowth1: "+4%",
					appRevDow1: "102,843",
					appNewDisplay1: "inline-block",
					appPositionChange1: "",
					appPositionChangeDisplay1: "none",
					appName2: "8 Ball Pool",
					appIcon2: "images/placeholder-app-icon-8ball.png",
					appPublisher2: "Miniclip",
					appNumberOfRatings2: "(3,247)",
					appPrice2: "Free",
					appGrowth2: "+8%",
					appRevDow2: "102,843",
					appNewDisplay2: "none",
					appPositionChange2: "-2",
					appPositionChangeDisplay2: "inline-block",
					appName3: "Bridge Constructor",
					appIcon3: "images/placeholder-app-icon-bridge.png",
					appPublisher3: "Headup Games GmbH &amp; Co KG",
					appNumberOfRatings3: "(3,247)",
					appPrice3: "$1.99",
					appGrowth3: "+6%",
					appRevDow3: "46,789",
					appNewDisplay3: "none",
					appPositionChange3: "5",
					appPositionChangeDisplay3: "inline-block",
				},
				{
					appName1: "Minecraft: Pocket Edition",
					appIcon1: "images/placeholder-app-icon-minecraft.png",
					appPublisher1: "Mojang",
					appNumberOfRatings1: "(10,458)",
					appPrice1: "$2.49",
					appGrowth1: "+4%",
					appRevDow1: "102,843",
					appNewDisplay1: "none",
					appPositionChange1: "-1",
					appPositionChangeDisplay1: "inline-block",
					appName2: "Thumb Drift - Furious One Touch Car Racing",
					appIcon2: "images/placeholder-app-icon-drift.png",
					appPublisher2: "SMG Studio",
					appNumberOfRatings2: "(156)",
					appPrice2: "Free",
					appGrowth2: "+6%",
					appRevDow2: "102,356",
					appNewDisplay2: "none",
					appPositionChange2: "119",
					appPositionChangeDisplay2: "inline-block",
					appName3: "Clash Royale",
					appIcon3: "images/placeholder-app-icon.jpg",
					appPublisher3: "Supercell",
					appNumberOfRatings3: "(2,406)",
					appPrice3: "$1.49",
					appGrowth3: "+8%",
					appRevDow3: "30,564",
					appNewDisplay3: "none",
					appPositionChange3: "4",
					appPositionChangeDisplay3: "inline-block",
				},
				{
					appName1: "8 Ball Pool",
					appIcon1: "images/placeholder-app-icon-8ball.png",
					appPublisher1: "Miniclip",
					appNumberOfRatings1: "(3,247)",
					appPrice1: "$0.99",
					appGrowth1: "+10%",
					appRevDow1: "247,926",
					appNewDisplay1: "none",
					appPositionChange1: "15",
					appPositionChangeDisplay1: "inline-block",
					appName2: "Bridge Constructor",
					appIcon2: "images/placeholder-app-icon-bridge.png",
					appPublisher2: "Headup Games GmbH &amp; Co KG",
					appNumberOfRatings2: "(3,247)",
					appPrice2: "Free",
					appGrowth2: "+10%",
					appRevDow2: "146,789",
					appNewDisplay2: "inline-block",
					appPositionChange2: "1",
					appPositionChangeDisplay2: "none",
					appName3: "Clash of Clans",
					appIcon3: "images/placeholder-app-icon-clash.png",
					appPublisher3: "Supercell",
					appNumberOfRatings3: "(78,001)",
					appPrice3: "$0.99",
					appGrowth3: "+10%",
					appRevDow3: "102,843",
					appNewDisplay3: "none",
					appPositionChange3: "",
					appPositionChangeDisplay3: "none",
				},
				{
					appName1: "Minecraft: Pocket Edition",
					appIcon1: "images/placeholder-app-icon-minecraft.png",
					appPublisher1: "Mojang",
					appNumberOfRatings1: "(10,458)",
					appPrice1: "$1.99",
					appGrowth1: "+4%",
					appRevDow1: "156,038",
					appNewDisplay1: "none",
					appPositionChange1: "-1",
					appPositionChangeDisplay1: "inline-block",
					appName2: "Thumb Drift - Furious One Touch Car Racing",
					appIcon2: "images/placeholder-app-icon-drift.png",
					appPublisher2: "SMG Studio",
					appNumberOfRatings2: "(156)",
					appPrice2: "Free",
					appGrowth2: "+6%",
					appRevDow2: "102,356",
					appNewDisplay2: "none",
					appPositionChange2: "119",
					appPositionChangeDisplay2: "inline-block",
					appName3: "Clash Royale",
					appIcon3: "images/placeholder-app-icon.jpg",
					appPublisher3: "Supercell",
					appNumberOfRatings3: "(2,406)",
					appPrice3: "$2.49",
					appGrowth3: "+100%",
					appRevDow3: "60,564",
					appNewDisplay3: "none",
					appPositionChange3: "",
					appPositionChangeDisplay3: "none",
				},
				{
					appName1: "Clash of Clans",
					appIcon1: "images/placeholder-app-icon-clash.png",
					appPublisher1: "Supercell",
					appNumberOfRatings1: "(78,001)",
					appPrice1: "Free",
					appGrowth1: "+4%",
					appRevDow1: "102,843",
					appNewDisplay1: "none",
					appPositionChange1: "",
					appPositionChangeDisplay1: "none",
					appName2: "8 Ball Pool",
					appIcon2: "images/placeholder-app-icon-8ball.png",
					appPublisher2: "Miniclip",
					appNumberOfRatings2: "(3,247)",
					appPrice2: "Free",
					appGrowth2: "+8%",
					appRevDow2: "102,843",
					appNewDisplay2: "none",
					appPositionChange2: "-2",
					appPositionChangeDisplay2: "inline-block",
					appName3: "Bridge Constructor",
					appIcon3: "images/placeholder-app-icon-bridge.png",
					appPublisher3: "Headup Games GmbH &amp; Co KG",
					appNumberOfRatings3: "(3,247)",
					appPrice3: "Free",
					appGrowth3: "+6%",
					appRevDow3: "46,789",
					appNewDisplay3: "none",
					appPositionChange3: "5",
					appPositionChangeDisplay3: "inline-block",
				},
				{
					appName1: "Minecraft: Pocket Edition",
					appIcon1: "images/placeholder-app-icon-minecraft.png",
					appPublisher1: "Mojang",
					appNumberOfRatings1: "(10,458)",
					appPrice1: "$1.49",
					appGrowth1: "+4%",
					appRevDow1: "102,843",
					appNewDisplay1: "none",
					appPositionChange1: "-1",
					appPositionChangeDisplay1: "inline-block",
					appName2: "Thumb Drift - Furious One Touch Car Racing",
					appIcon2: "images/placeholder-app-icon-drift.png",
					appPublisher2: "SMG Studio",
					appNumberOfRatings2: "(156)",
					appPrice2: "Free",
					appGrowth2: "+6%",
					appRevDow2: "102,356",
					appNewDisplay2: "none",
					appPositionChange2: "119",
					appPositionChangeDisplay2: "inline-block",
					appName3: "Clash Royale",
					appIcon3: "images/placeholder-app-icon.jpg",
					appPublisher3: "Supercell",
					appNumberOfRatings3: "(2,406)",
					appPrice3: "$0.99",
					appGrowth3: "+8%",
					appRevDow3: "30,564",
					appNewDisplay3: "none",
					appPositionChange3: "4",
					appPositionChangeDisplay3: "inline-block",
				}];